title: Saiprakash   Dommati # your name (or website title) here
logo: "/sai.1.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Senior DevOps Engineer
  <br><br>
  <a href="mailto:dommatisaiprakash44@gmail.com">dommatisaiprakash44@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/Saiprakash Dommati/">LinkedIn Profile</a>
  <br>
  <a href="https://www.github.com/saiprakash102/">github</a> 
theme: jekyll-theme-minimal
